{% set setup_data = load_setup_py_data(setup_file="../src/interface_py/setup.py", from_recipe_dir=True) %}
{% set build_number = load_file_regex(load_file='src/interface_py/h2o4gpu/BUILD_INFO.txt', regex_pattern='suffix="\+(\w+)_.*"').group(1) %}
{% set commit = load_file_regex(load_file="src/interface_py/h2o4gpu/BUILD_INFO.txt", regex_pattern='commit="(\w+)"').group(1) %}
{% set build_date = load_file_regex(load_file='src/interface_py/h2o4gpu/BUILD_INFO.txt', regex_pattern='build_date="(\d+)"').group(1) %}
{% set py = 'py' ~ CONDA_PY %}
{% set platform = SUBDIR|replace('-','') %}
{% set build_string = platform ~ '_' ~ py ~ '_' ~ build_date ~ '_' ~ commit|truncate(9,end='') ~ '_' ~ build_number %}
{% set version = load_file_regex(load_file='src/interface_py/h2o4gpu/BUILD_INFO.txt', regex_pattern='base_version="([\d.]+)"').group(1) %}

package:
  name: "h2o4gpu"
  version: "{{ version }}"

source:
  path: ../

build:
  string: "{{ build_string }}"
  number: 0

requirements:
  build:
    - python {{ python }}
    - apipkg==1.4
    - attrs==17.3.0
    - execnet==1.5.0
    - pluggy==0.6.0
    - py==1.5.2
    - six==1.11.0
    - yapf==0.17.0
    - coverage==4.4.1
    - sphinx==1.5.6
    - sphinx_rtd_theme==0.2.4
    - pillow==4.2.1
    - wheel==0.31.1
    - cython=0.27.3
    - h2o==3.18.0.11
    - pandas==0.22.0
    - numpy==1.14.5
    - nbconvert==5.3.1
    - nbformat=4.3.0
    - notebook==5.4.1
    - numba==0.36.2
    - feather-format==0.4.0
    - psutil==5.4.5
    - awscli==1.15.6
    - matplotlib==2.0.2
    - llvmlite==0.21
    - pyzmq==17.0.0
    - scipy==1.1.0
  run:
    - python {{ python }}
    - apipkg==1.4
    - attrs==17.3.0
    - execnet==1.5.0
    - pluggy==0.6.0
    - py==1.5.2
    - six==1.11.0
    - yapf==0.17.0
    - coverage==4.4.1
    - sphinx==1.5.6
    - sphinx_rtd_theme==0.2.4
    - pillow==4.2.1
    - wheel==0.31.1
    - cython=0.27.3
    - h2o==3.18.0.11
    - pandas==0.22.0
    - numpy==1.14.5
    - nbconvert==5.3.1
    - nbformat=4.3.0
    - notebook==5.4.1
    - numba==0.36.2
    - feather-format==0.4.0
    - psutil==5.4.5
    - awscli==1.15.6
    - matplotlib==2.0.2
    - llvmlite==0.21
    - pyzmq==17.0.0
    - scipy==1.1.0

test:
  imports:
    - h2o4gpu

about:
  home: "{{ setup_data.url }}"
  license: "{{ setup_data.license }}"
  summary: "H2O4GPU is a collection of GPU solvers by H2O.ai with APIs in Python and R."
  doc_url: https://github.com/h2oai/h2o4gpu/blob/master/README.md
  dev_url: https://github.com/h2oai/h2o4gpu

extra:
  maintainers:
    - h2oai


